services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    environment:
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/panels.json
      - GF_INSTALL_PLUGINS=volkovlabs-image-panel,marcusolsson-dynamictext-panel,grafana-llm-app
    volumes:
      - ./dist:/var/lib/grafana/plugins/marcusolsson-static-datasource
      - ./provisioning:/etc/grafana/provisioning

  playwright:
    build:
      context: .
      dockerfile: test/Dockerfile
    environment:
      - GRAFANA_URL=http://127.0.0.1:3000
    volumes:
      - ./test:/app/test
      - ./playwright-report:/app/playwright-report
    network_mode: host
    profiles:
      - playwright
